import tfm__unit_interval
import tfm__2D_rows_sum_to_one__log
import tfm__2D_rows_sum_to_one__stickbreak

# Make a few functions easily available
logistic_sigmoid = tfm__unit_interval.logistic_sigmoid
inv_logistic_sigmoid = tfm__unit_interval.inv_logistic_sigmoid

from log_logistic_sigmoid import log_logistic_sigmoid